//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADA.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCADA.Configuration.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; failed to validate by validation rule for config item &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentException_CustomizeValidation {
            get {
                return ResourceManager.GetString("ArgumentException_CustomizeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; failed to validate by regex &apos;{1}&apos; for config item &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentException_RegexValidation {
            get {
                return ResourceManager.GetString("ArgumentException_RegexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is out of range for config item &apos;{1}&apos;. Min: {2}, Max: {3}..
        /// </summary>
        internal static string ArgumentOutOfRangeException_MaxMin {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_MaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t convert to a boolean for ‘{1}’..
        /// </summary>
        internal static string InvalidCastException_CannotConvert2Boolean {
            get {
                return ResourceManager.GetString("InvalidCastException_CannotConvert2Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t convert to a Color for ‘{1}’..
        /// </summary>
        internal static string InvalidCastException_CannotConvert2Color {
            get {
                return ResourceManager.GetString("InvalidCastException_CannotConvert2Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t convert to a DateTime for ‘{1}’..
        /// </summary>
        internal static string InvalidCastException_CannotConvert2DateTime {
            get {
                return ResourceManager.GetString("InvalidCastException_CannotConvert2DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t convert to a decimal for ‘{1}’..
        /// </summary>
        internal static string InvalidCastException_CannotConvert2Decimal {
            get {
                return ResourceManager.GetString("InvalidCastException_CannotConvert2Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t convert to a integer for ‘{1}’..
        /// </summary>
        internal static string InvalidCastException_CannotConvert2Integer {
            get {
                return ResourceManager.GetString("InvalidCastException_CannotConvert2Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid path string for ‘{1}’..
        /// </summary>
        internal static string InvalidCastException_CannotConvert2Path {
            get {
                return ResourceManager.GetString("InvalidCastException_CannotConvert2Path", resourceCulture);
            }
        }
    }
}
